### ISSUE TITLE
Over sampling x8 for pressure

### ISSUE THREAD

**Issue by wadoadi** [rv701/SPL06-007#1]
Thanks for this and it works for my sensor.

Not sure if this is a bug or me miss reading the spec!?
from code
  Serial.println("Setting pressure configuration register - 0X03");
  i2c_eeprom_write_uint8_t(EEPROM_CHIP_ADDRESS, 0X06, 0x03); // Pressure 8x oversampling

06 hex is 0110 
The spec says 0110 is 64 x oversampling PM_PRC bits 0- 3. 

Is the code comment wrong or am I miss reading the spec?

**Comment by rv701** [comment]
0x06 is the register address and 0x03 is the data being written to the register. Thanks for the feedback.

void i2c_eeprom_write_uint8_t(  uint8_t deviceaddress, uint8_t eeaddress, uint8_t data )

**Comment by wadoadi** [comment]
ok thank you, I misread the "Setting pressure configuration register - 0X03"  would have been clearer for me at least if it had been "Setting pressure configuration register to - 0X03"

thanks for your work it has been very helpful
